### ISSUE TITLE
Fix Synchronous XMLHttpRequest Depreciation on File Upload

### ISSUE THREAD

**Issue by asayler** [asayler/COG-Web#14]
jquery-2.1.1.min.js:4 - Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

**Comment by hexacyanide** [comment]
I was inspecting the code at [js/cog_api.js#L58](https://github.com/asayler/COG-Web/blob/bb62e8b5762a74d55d3fe305e27206c908bf0b7c/js/cog_api.js#L58); is there any specific reason that the request is performed synchronously? On a cursory inspection, the code already appears to be written in such a way that it would work fine even if the request were nonblocking.

**Comment by asayler** [comment]
No real reason, just laziness (and lack of js expertise) on my part. Patches welcome!

**Comment by asayler** [comment]
Also, using async we may need some form of progress bar or other UI interaction to make sure the user doesn't try to change any settings or otherwise disrupt the submission fow while the upload is in progress. Not sure if that will be an issue or not, but may be worth considering.

**Comment by hexacyanide** [comment]
Since the current code already uses callbacks, I believe the functionality is already in place, but I do think it'd be worthwhile to implement a progress feature of some sort. For larger file uploads, where a user might mistake long upload times for an unresponsive web page, a progress indicator might lead to less prematurely-terminated file uploads on the API server side.
